version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run:
          name: "Deploy to server"
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            cd scripts
            sshpass -p "${PASSWORDSERVER}" scp -o StrictHostKeyChecking=no -r deploy.sh root@${IPSERVER}:/home/install
            sshpass -p "${PASSWORDSERVER}" ssh -o StrictHostKeyChecking=no root@${IPSERVER} 'cd /home/install && sh deploy.sh'
  mysql:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run:
          name: "Login Mysql"
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            cd scripts
            sshpass -p "${PASSWORDSERVER}" scp -o StrictHostKeyChecking=no -r mysql/mysql.sh root@${IPSERVER}:/home/install
            sshpass -p "${PASSWORDSERVER}" ssh -o StrictHostKeyChecking=no root@${IPSERVER} 'cd /home/install && sh mysql.sh'
workflows:
  version: 2
  deploy-server:
    jobs:
      - deploy:
          context: phpmvc
          filters:
            branches:
              only:
                - master
      - mysql:
          context: phpmvc