version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run:
          name: "What PAss"
          command: echo ${PASSWORDSERVER}
      - run:
          name: "What IP"
          command: echo ${IPSERVER}
      - run:
          name: "Deploy to server"
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            ls -al
            sshpass -p "${PASSWORDSERVER}" scp -o StrictHostKeyChecking=no -r deploy.sh root@${IPSERVER}:/install
            sshpass -p "${PASSWORDSERVER}" ssh -o StrictHostKeyChecking=no root@${IPSERVER} 'cd /install && sh deploy.sh'
workflows:
  version: 2
  build-and-test:
    jobs:
      - deploy:
          context: phpmvc
          filters:
            branches:
              only:
                - setup-ci
