version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run:
          name: "Deploy to server"
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            ls -al
workflows:
  version: 2
  build-and-test:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - setup-ci
