<?php

const LANGUAGES = [
    // User List
    'full_name' => 'Họ và tên',
    'role' => 'Quyền',
    'email' => 'Email',
    'phone' => 'Điện thoại',
    'birthday' => 'Ngày sinh',
    'status' => 'Trạng thái',
    'action' => 'Hành động',
    'user_list' => 'Danh sách user',
    'total_mess' => 'Bạn có tổng cộng',
    'user' => 'người dùng',
    'add_user' => 'Thêm người dùng',
    'view_detail' => 'Xem chi tiết',
    'reset_pass' => 'Reset mật khẩu',
    'delete_user' => 'Xóa người dùng',
    // User detail
    'login_information' => 'Thông tin đăng nhập',
    'personal' => 'Cá nhân',
    'first_name' => 'Họ đệm',
    'last_name' => 'Tên',
    'email_address' => 'Địa chỉ email',
    'active' => 'Đã kích hoạt',
    'inactive' => 'Chưa kích hoạt',
    'administrator_permission' => 'Quản trị',
    'doctor_permission' => 'Bác sĩ',
    'user_permission' => 'Người dùng',
    'personal_information' => 'Thông tin cá nhân',
    'way' => 'Đường',
    'district' => 'Phường/xã',
    'wards' => 'Quận/huyện',
    'province' => 'Tỉnh/thành phố',
    'identity_card' => 'CMND/CCCD',
    'date_of_birth' => 'Ngày sinh',
    'gender' => 'Giới tính',
    'edit_user' => 'Chỉnh sửa người dùng',
    'change_avatar' => 'Đổi ảnh đại diện',
    'choose_file' => 'Chọn file',
    'users' => 'Người dùng',
    'user_id' => 'Mã người dùng',
    'password' => 'Mật khẩu',
    'confirm_password' => 'Xác nhận mật khẩu',
    'language' => 'Ngôn ngữ',
    'english' => 'Tiếng Anh',
    'vietnamese' => 'Tiếng Việt',
    'male' => 'Nam',
    'female' => 'Nữ'
];
